GET http://localhost/v1/stats/version
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJTZXNzaW9uIjoxLCJTZXNzaW9uRXhwaXJlIjoxNjc5MDUzNDkxLCJVc2VyIjoxLCJVc2VyUm9sZSI6ImFkbWluaXN0cmF0b3IiLCJVc2VybmFtZSI6InNoZWV5IiwiYXVkIjpbIkNob2NvbGF0ZSB1c2VyIl0sImlhdCI6MTY3Nzg0Mzg5MSwiaXNzIjoic2hlZXkifQ.pgn8HwxxVjfJOzE28h6ouBLG4Tv6vxJjAPLwDyeqc014XuQf5ulwr3DvB_dvj2IfZvpBdc1DfZw8hGgobJy1AQ

