package errors

const (
	_ RequestErrorCode = iota
	RequestInternalServerError
	RequestBadRequestData
	RequestBadParameter
	ReuqestRoleNotFound
	RequestUserNotFound
	RequestRoomNotFound
	RequestUsernameTaken
	RequestUsernameDuplicate
	RequestUsernameNotMeetConstraint
	RequestPasswordNotMeetConstraint
	RequestPasswordIncorrect
	RequestNotLoggedIn
	RequestPermissionDenied
	RequestJwtVerificationFailed
	RequestCorruptJwtPayload
	RequestSessionExpire
	RequestOneLastAdminDeletionNotAllowed
	RequestInvalidRoomUID
	RequestInvalidRoomID
	RequestInvalidLogFilter
	RequestInvalidLogFilterBeforeTimestamp
	RequestInvalidLogFilterAfterTimestamp
	RequestNotRoomOwner
	RequestUnknownRoomActionType
	RequestUnknownRoomPermissionType
	RequestUnknownRoomPermissionItemType
	RequestPermissionItemAlreadyExistError
	RequestPermissionItemNotExistError
	RequestLogRetrivalLimitTooBig
	RequestLogRetrivalInvalidTimeRange
	RequestRoomCountReachedMax
)

const (
	_ DatabaseErrorCode = iota | (0x02 << 56)
	DatabaseCreateNewSessionError
	DatabaseCreateAdminAccountError
	DatabaseCreateUserAccountError
	DatabaseCreatePermissionItemError

	DatabaseCountAdminAccountError
	DatabaseCountPermissionItemError
	DatabaseCountLogsError

	DatabaseLookupUsernamesError
	DatabaseLookupRolesError
	DatabaseLookupLabelsError
	DatabaseLookupUserError
	DatabaseLookupRoomError
	DatabaseLookupLogsError

	DatabaseDeleteUserError

	DatabaseSetUserRoleError
	DatabaseSetUserPasswordError

	DatabaseUpdateRoomPermissionTypeError
	DatabaseUpdateRoomStatusError
	DatabaseUpdareRoomPushKeyError

	DatabaseClearRoomPermissionItemError
)
